### ISSUE TITLE
[BUG] Yolov5 dataset.yaml support is incomplete

### ISSUE THREAD

**Issue by nmichlo** [voxel51/fiftyone#2381]
### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04): 20.04
-   **Python version** (`python --version`): 3.10
-   **FiftyOne version** (`fiftyone --version`): 0.18.0
-   **FiftyOne installed from** (pip or source): pip

### Commands to reproduce

Try and load a dataset with a list of directories instead of a single image directory.

```
fiftyone app view -d my_yolo_dataset -t fiftyone.types.YOLOv5Dataset
```

### Describe the problem

The yolov5 dataset.yaml spec indicates that it supports lists of image/label directories, not just a single directory. Fiftyone only supports a single image directory, eg:
```yaml
names:
- class_name_0
- class_name_1
nc: 2
train: custom_data/images/train
```

However, you should be able to specify a list of image directories, that correspond to label directories.
```yaml
names:
- class_name_0
- class_name_1
nc: 2
path: /path/to/dataset/root
train:
  - custom_data_0/images/train
  - custom_data_1/images/train
```

The second last item in these paths `images` should be replaced with `labels` to obtain the labels directories.

### Code to reproduce issue

N/A

### Other info/logs

Reference:
- https://github.com/ultralytics/yolov5/blob/7f5724ba4b3e421d4c9162742810c52248d06ecd/utils/dataloaders.py#L425-L584

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [x] No. I cannot contribute a bug fix at this time
