### ISSUE TITLE
[BUG] Example docker-compose.yml not working

### ISSUE THREAD

**Issue by speendo** [voxel51/fiftyone#5511]
### Describe the problem

I tried to run fiftyone in Docker, using the example docker-compose.yml file from https://hub.docker.com/r/voxel51/fiftyone .

After replacing the volume directory (as intended) I tried to start the container which resulted in this error:

```
$ docker compose up
[+] Running 2/2
 ✔ Network docker_default       Created                                                                                                                             0.3s 
 ✔ Container docker-fiftyone-1  Created                                                                                                                             0.3s 
Attaching to fiftyone-1
fiftyone-1  | python: can't open file '/usr/local/lib/python/dist-packages/fiftyone/server/main.py': [Errno 2] No such file or directory
fiftyone-1 exited with code 2
```

I then removed the line

    command: ['python', '/usr/local/lib/python/dist-packages/fiftyone/server/main.py', '--port', '5151']

from the docker compose file and started the container again. This way the container started.

### Code to reproduce issue

1. Create a file `docker-compose.yml`
2. Copy the example content from https://hub.docker.com/r/voxel51/fiftyone (see below)

```
services:
  fiftyone:
    command: ['python', '/usr/local/lib/python/dist-packages/fiftyone/server/main.py', '--port', '5151']
    environment:
      FIFTYONE_DEFAULT_APP_ADDRESS: 0.0.0.0
    image: voxel51/fiftyone:latest
    ports:
      - 5151:5151
    volumes:
      - type: bind
        source: some-local-directory
        target: /fiftyone
```

3. Replace `some-local-directory` with something reasonable
4. Run the container with `docker compose up`
5. Find the error message mentioned above

### System information

-   **OS Platform and Distribution**: Debian Testing (13)
-   **Python version** (`python --version`): Docker - irrelevant
-   **FiftyOne version** (`fiftyone --version`): Docker - irrelevant
-   **FiftyOne installed from** (pip or source): Docker (voxel51/fiftyone:latest)

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [X] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

### Fix

Remove the line

    command: ['python', '/usr/local/lib/python/dist-packages/fiftyone/server/main.py', '--port', '5151']

from the docker-compose example file.

**Comment by afoley587** [comment]
@benjaminpkane I don't think it's a README since it's a docker repo description. I'll address and close when done!

**Comment by afoley587** [comment]
@benjaminpkane @speendo - the docker docs have been updated:

```yaml
services:
  fiftyone:
    command: ["python", "-m", "fiftyone.server.main", "--port", "5151"]
    environment:
      FIFTYONE_DEFAULT_APP_ADDRESS: 0.0.0.0
    image: voxel51/fiftyone:latest
    ports:
      - 5151:5151
    volumes:
      - type: bind
        source: some-local-directory
        target: /fiftyone
```

Note the CMD is still there and is the default `server` target listed [here](https://github.com/voxel51/fiftyone/blob/8a0b9e5324b3e0a0def907780d1931338d669d33/Dockerfile#L129).

Thanks for catching!
